# Dependencies
markdown:         kramdown
highlights:         true

# Permalinks
permalink:        /:year/:title/

# Setup
title:            Unchart
url:              http://unchart.com
paginate:         1
baseurl:          /
author:
  name:           Jonathan Ploudre
  url:            https://twitter.com/jploudre
  email:          jploudre@gmail.com

category_archive: category_archive